Lineup/ViewModels/AccountHomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Logics.Entities;

namespace Lineup.ViewModels
{
    public class AccountHomeViewModel
    {
        public List<Team> Teams = new List<Team>();
    }
}

Lineup/ViewModels/TeamHomeViewModel.cs
using Logics.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lineup.ViewModels
{
    public class TeamHomeViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public List<Player> Players { get; set; }

        public List<Formation> Formations { get; set; }
    }
}

Lineup/ViewModels/TeamViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Lineup.ViewModels
{
    public class TeamViewModel
    {
        [Required(ErrorMessage = "You need to fill in a team name.")]
        public string Name { get; set; }

        public int Id { get; set; }
    }
}

Lineup/Controllers/FormationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lineup.ViewModels;
using Logics.Entities;
using Logics.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Data.Enums;

namespace Lineup.Controllers
{
    [Authorize]
    public class FormationController : Controller
    {
        private readonly IFormationService _FormationService;
        private readonly IPlayerService _PlayerService;

        public FormationController(IFormationService formationService, IPlayerService playerService)
        {
            _FormationService = formationService;
            _PlayerService = playerService;
        }

        [HttpGet]
        public async Task<IActionResult> AddFormation(int teamId)
        {
            List<Player> players = new List<Player>();
            players = await _PlayerService.GetAllPlayers(teamId);

            //check if the team has at least 11 players
            if (players.Count >= 11)
            {
                List<Position> positions = new List<Position>();
                foreach (Position position in Enum.GetValues(typeof(Position)))
                {
                    positions.Add(position);
                }
                return View(new FormationViewModel { Players = players, Positions = positions, TeamId = teamId });
            }
            return RedirectToAction("Teamhome", "Team", new { id = teamId });
        }

        [HttpPost]
        public async Task<IActionResult> AddFormation(FormationViewModel model)
        {
            List<Player> players = await _PlayerService.GetAllPlayers(model.TeamId);
            model.Players = players;
            model.Positions = GetAllPositions();

            if (ModelState.IsValid)
            {
                List<Position> submittedPositions = new List<Position>();
                foreach (var player in players)
                {
                    Position position = (Position)Enum.Parse(typeof(Position), Request.Form[player.Id.ToString()], true);
                    submittedPositions.Add(position);
                    
                }
                var errors = _FormationService.CheckFormation(submittedPositions);
                //check if there are exactly 11 field players and only 1 keeper
                if (errors.Count == 0)
                {
                        Formation formation = new Formation()
                        {
                            Name = model.Name,
                            TeamId = model.TeamId
                        };
                        int id = await _FormationService.AddFormation(formation);
                        foreach (var player in players)
                        {
                            Position position = (Position)Enum.Parse(typeof(Position), Request.Form[player.Id.ToString()], true);
                            PlayerPosition pp = new PlayerPosition()
                            {
                                PlayerId = player.Id,
                                Position = position,
                                FormationId = id
                            };
                            await _FormationService.AddPlayerPosition(pp);
                        }
                        return RedirectToAction("TeamHome", "Team", new { id = model.TeamId });
                }
                foreach (var error in errors)
                {
                    ModelState.AddModelError("", error);
                }
                
                return View(model);
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Formation(int id)
        {
            List<PlayerPosition> playerPositions = await _FormationService.GetAllPlayerPositions(id);
            Formation formation = await _FormationService.GetFormation(id);
            return View(new FormationViewModel() { Id = id, Name = formation.Name, PlayerPositions = playerPositions, TeamId = formation.TeamId });
        }

        [HttpGet]
        public async Task<IActionResult> DeleteFormation(int id, int teamId)
        {
            await _FormationService.DeleteFormation(id);
            return RedirectToAction("TeamHome", "Team", new { Id = teamId});
        }

        [HttpGet]
        public async Task<IActionResult> EditFormation(int id)
        {
            List<PlayerPosition> playerPositions = await _FormationService.GetAllPlayerPositions(id);
            Formation formation = await _FormationService.GetFormation(id);
            List<Position> positions = new List<Position>();
            foreach (Position position in Enum.GetValues(typeof(Position)))
            {
                positions.Add(position);
            }
            return View(new FormationViewModel() { Id = id, Name = formation.Name, PlayerPositions = playerPositions, Positions = positions, TeamId = formation.TeamId });
        }

        [HttpPost]
        public async Task<IActionResult> EditFormation(FormationViewModel model)
        {
            List<PlayerPosition> playerPositions = await _FormationService.GetAllPlayerPositions(model.Id);
            model.PlayerPositions = playerPositions;
            model.Positions = GetAllPositions();
            if (ModelState.IsValid)
            {
                List<Player> players = await _PlayerService.GetAllPlayers(model.TeamId);
                List<Position> submittedPositions = new List<Position>();
                foreach (var player in players)
                {
                    Position position = (Position)Enum.Parse(typeof(Position), Request.Form[player.Id.ToString()], true);
                    submittedPositions.Add(position);

                }
                var errors = _FormationService.CheckFormation(submittedPositions);

                if (errors.Count == 0)
                {
                    Formation formation = new Formation()
                    {
                        Id = model.Id,
                        TeamId = model.TeamId,
                        Name = model.Name
                    };
                    await _FormationService.EditFormation(formation);

                    foreach (var pp in playerPositions)
                    {
                        Position position = (Position)Enum.Parse(typeof(Position), Request.Form[pp.PlayerId.ToString()], true);
                        PlayerPosition playerPosition = new PlayerPosition()
                        {
                            Id = pp.Id,
                            PlayerId = pp.PlayerId,
                            Position = position,
                            FormationId = model.Id

                        };
                        await _FormationService.EditPlayerPosition(playerPosition);
                    }
                    return RedirectToAction("TeamHome", "Team", new { id = model.TeamId });
                }
                foreach (var error in errors)
                {
                    ModelState.AddModelError("", error);
                }

                return View(model);
            }
            return View(model);
        }

        public List<Position> GetAllPositions()
        {
            List<Position> positions = new List<Position>();
            foreach (Position position in Enum.GetValues(typeof(Position)))
            {
                positions.Add(position);
            }
            return positions;
        }
    }
}

Lineup/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lineup.ViewModels;
using Logics.Entities;
using Logics.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Lineup.Controllers
{
    [Authorize]
    public class PlayerController : Controller
    {
        private readonly IPlayerService _PlayerService;

        public PlayerController(IPlayerService playerService)
        {
            _PlayerService = playerService;
        }

        [HttpGet]
        public IActionResult AddPlayer(int teamId)
        {
            return View(new PlayerViewModel() { TeamId = teamId});
        }

        [HttpPost]
        public async Task<IActionResult> AddPlayer(PlayerViewModel model)
        {
            if (ModelState.IsValid)
            {
                Player player = new Player()
                {
                    Name = model.Name,
                    Age = model.Age,
                    TeamId = model.TeamId
                };
                await _PlayerService.AddPlayer(player);
                return RedirectToAction("TeamHome", "Team", new { id = model.TeamId });
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditPlayer(int id, int teamId)
        {
            Player player = await _PlayerService.GetPlayer(id);
            return View(new PlayerViewModel() { Name = player.Name, Age = player.Age, PlayerId = player.Id, TeamId = teamId });
        }

        [HttpPost]
        public async Task<IActionResult> EditPlayer(PlayerViewModel model)
        {
            if (ModelState.IsValid)
            {
                Player player = new Player()
                {
                    Name = model.Name,
                    Age = model.Age,
                    Id = model.PlayerId,
                    TeamId = model.TeamId
                };
                await _PlayerService.EditPlayer(player);
                return RedirectToAction("TeamHome", "Team", new { id = model.TeamId });
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DeletePlayer(int id, int teamId)
        {
            await _PlayerService.DeletePlayer(id);
            return RedirectToAction("TeamHome", "Team", new { id = teamId });
        }
    }
}

Lineup/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lineup.ViewModels;
using Logics.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Logics.Entities;
using Microsoft.AspNetCore.Authorization;

namespace Lineup.Controllers
{
    [Authorize]
    public class TeamController : Controller
    {
        private readonly IIdentityService _IdentityService;
        private readonly ITeamService _TeamService;
        private readonly IPlayerService _PlayerService;
        private readonly IFormationService _FormationService;

        public TeamController(IIdentityService identityService, ITeamService teamService, IPlayerService playerService, IFormationService formationService)
        {
            _IdentityService = identityService;
            _TeamService = teamService;
            _PlayerService = playerService;
            _FormationService = formationService;
        }

        [HttpGet]
        public async Task<IActionResult> AccountHome()
        {
            var userClaims = HttpContext.User;
            var user = await _IdentityService.GetUserAsync(userClaims.Identity.Name);
            var teams = await _TeamService.GetAllTeams(user.Id);
            return View(new AccountHomeViewModel { Teams = teams });
        }

        [HttpGet]
        public IActionResult AddTeam()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddTeam(TeamViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userClaims = HttpContext.User;
                var user = await _IdentityService.GetUserAsync(userClaims.Identity.Name);
                Team team = new Team()
                {
                    UserId = user.Id,
                    Name = model.Name
                };
                await _TeamService.AddTeam(team);
                return RedirectToAction(nameof(AccountHome));
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteTeam(int id)
        {
            await _TeamService.DeleteTeam(id);
            return RedirectToAction(nameof(AccountHome));
        }

        [HttpGet]
        public async Task<IActionResult> TeamHome(int id)
        {
            var team = await _TeamService.GetTeam(id);
            var players = await _PlayerService.GetAllPlayers(id);
            var formations = await _FormationService.GetAllFormations(id);
            return View(new TeamHomeViewModel { Id = id, Players = players, Formations = formations, Name = team.Name  });
        }

        [HttpGet]
        public async Task<IActionResult> EditTeam(int id)
        {
            Team team = await _TeamService.GetTeam(id);
            return View(new TeamViewModel() { Name = team.Name, Id = team.Id});
        }

        [HttpPost]
        public async Task<IActionResult> EditTeam(TeamViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userClaims = HttpContext.User;
                var user = await _IdentityService.GetUserAsync(userClaims.Identity.Name);
                Team team = new Team()
                {
                    Name = model.Name,
                    Id = model.Id,
                    UserId = user.Id
                };
                await _TeamService.EditTeam(team);
                return RedirectToAction(nameof(AccountHome));
            }
            return View(model);
        }
    }
}

Lineup/Views/Team/AccountHome.cshtml
@model AccountHomeViewModel
@{
    ViewData["Title"] = "MyTeams";
}

<h1>My teams</h1>
    <a asp-controller="Team" asp-action="AddTeam" class="btn btn-primary">Add team</a>
@if (Model != null)
{
    foreach (var team in Model.Teams)
    {
        <center>
        <div class="card" style="width:30%">
                <center>
                    <h2 class="card-header">@team.Name</h2>
                    <div class="card-body">
                        <a asp-controller="Team" asp-action="Teamhome" asp-route-id=@team.Id class="btn btn-primary">View team</a>
                        <a asp-controller="Team" asp-action="EditTeam" asp-route-id="@team.Id" class="btn btn-secondary">Edit teamname</a>
                        <a asp-controller="Team" asp-action="DeleteTeam" asp-route-id=@team.Id class="btn btn-danger">Delete team</a>
                    </div>
                </center>
        </div>
            </center>
    }
}

Lineup/Views/Team/AddTeam.cshtml
@model AddTeamViewModel

@{
    ViewData["Title"] = "Add team";
}

<h1>Add new team</h1>
<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TeamName"></label>
                <input asp-for="TeamName" class="form-control" />
            </div>
            <button type="submit" class="btn btn-primary">Add team</button>
        </form>
    </div>
</div>

Lineup/Views/Team/EditTeam.cshtml
@model TeamViewModel

@{
    ViewData["Title"] = "Edit player";
}

<h1>Edit teamname</h1>
<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" value=@Model.Name />
                <input type="hidden" asp-for="Id" value=@Model.Id />
            </div>
            <button type="submit" class="btn btn-primary">Edit teamname</button>
        </form>
    </div>
</div>

Lineup/Views/Team/Team.cshtml
@model TeamViewModel
@{
    ViewData["Title"] = "";
}

<h1>My teams</h1>
<a asp-controller="Player" asp-action="AddPlayer" class="btn btn-primary">Add player</a>
<a asp-controller="Formation" asp-action="AddFormation" class="btn btn-primary">Add formation</a>
@if (Model != null)
{
    foreach (var player in Model.Players)
    {
        <center>
            <div class="card" style="width:30%">
                <center>
                    <h2 class="card-header">@player.Name</h2>
                    <div class="card-body">
                        <h5 class="card-text">Age: @player.Age</h5>
                        <a asp-controller="Player" asp-action="EditPlayer" asp-route-id=@player.Id class="btn btn-primary">Edit player</a>
                        <a asp-controller="Player" asp-action="DeletePlayer" asp-route-id=@player.Id class="btn btn-danger">Delete player</a>
                    </div>
                </center>
            </div>
        </center>
    }

    foreach (var formation in Model.Formations)
    {
        <center>
            <div class="card" style="width:30%">
                <center>
                    <h2 class="card-header">@formation.Name</h2>
                    <div class="card-body">
                        <a asp-controller="Formation" asp-action="ViewFormation" asp-route-id=@formation.Id class="btn btn-primary">View Formation</a>
                        <a asp-controller="Formation" asp-action="DeleteFormation" asp-route-id=@formation.Id class="btn btn-danger">Delete Formation</a>
                    </div>
                </center>
            </div>
        </center>
    }
}

Lineup/Views/Team/TeamHome.cshtml
@model TeamHomeViewModel
@{
    ViewData["Title"] = "";
}

<h1>@Model.Name</h1>
<div class="center">
    <a asp-controller="Player" asp-action="AddPlayer" asp-route-teamId=@Model.Id class="btn btn-primary">Add player</a>
    <a asp-controller="Formation" asp-action="AddFormation" asp-route-teamId=@Model.Id class="btn btn-primary">Add formation</a>
    <p class="text-danger">@ViewBag.ErrorMessage</p>
</div>
@if (Model != null)
{
    <div class="float-left w-50 mb-md-5">
    @foreach (var player in Model.Players)
    {
        <center>
            <div class="card w-100" style="width:30%">
                <center>
                    <h2 class="card-header">@player.Name</h2>
                    <div class="card-body">
                        <h5 class="card-text">Age: @player.Age</h5>
                        <a asp-controller="Player" asp-action="EditPlayer" asp-route-id=@player.Id asp-route-teamId="@Model.Id" class="btn btn-primary">Edit player</a>
                        <a asp-controller="Player" asp-action="DeletePlayer" asp-route-id=@player.Id asp-route-teamId="@Model.Id" class="btn btn-danger">Delete player</a>
                    </div>
                </center>
            </div>
        </center>
    }
        </div>
    <div class="float-right w-50 mb-md-5">
    @foreach (var formation in Model.Formations)
    {
        <center>
            <div class="card w-100" style="width:30%">
                <center>
                    <h2 class="card-header">@formation.Name</h2>
                    <div class="card-body">
                        <a asp-controller="Formation" asp-action="Formation" asp-route-id=@formation.Id class="btn btn-primary">View Formation</a>
                        <a asp-controller="Formation" asp-action="DeleteFormation" asp-route-id=@formation.Id asp-route-teamId="@Model.Id" class="btn btn-danger">Delete Formation</a>
                    </div>
                </center>
            </div>
        </center>
    }
        </div>
}